version: "3"

services:
  client:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: guardarian-page
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    stdin_open: true
    tty: true
