version: "3"

services:
  client:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        VITE_PORT: ${VITE_PORT}
    container_name: guardarian-page
    ports:
      - "${EXPOSE_PORT}:${VITE_PORT}"
    volumes:
      - .:/app
      - /app/node_modules
    stdin_open: true
    tty: true
